// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJAFcewZpyHcLjjJEJJE6z3tVX-3hltz4',
    appId: '1:477890680323:web:9e55cedc2308e23a30a036',
    messagingSenderId: '477890680323',
    projectId: 'netravest-326c7',
    authDomain: 'netravest-326c7.firebaseapp.com',
    storageBucket: 'netravest-326c7.firebasestorage.app',
    measurementId: 'G-4BNLVX3WDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOzNs1Tos9GVr7nkKza26KPu52UA9_MMg',
    appId: '1:477890680323:android:2b5581c0357a846830a036',
    messagingSenderId: '477890680323',
    projectId: 'netravest-326c7',
    storageBucket: 'netravest-326c7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAleVA3c35rvbsQW4CnKPWuw7qeujWpG-U',
    appId: '1:477890680323:ios:f5d29c430c44726330a036',
    messagingSenderId: '477890680323',
    projectId: 'netravest-326c7',
    storageBucket: 'netravest-326c7.firebasestorage.app',
    iosClientId: '477890680323-f4einoqfem8dsb2se7r74aqedvkq4bjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.netravest',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAleVA3c35rvbsQW4CnKPWuw7qeujWpG-U',
    appId: '1:477890680323:ios:f5d29c430c44726330a036',
    messagingSenderId: '477890680323',
    projectId: 'netravest-326c7',
    storageBucket: 'netravest-326c7.firebasestorage.app',
    iosClientId: '477890680323-f4einoqfem8dsb2se7r74aqedvkq4bjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.netravest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJAFcewZpyHcLjjJEJJE6z3tVX-3hltz4',
    appId: '1:477890680323:web:4159c15e1706c54c30a036',
    messagingSenderId: '477890680323',
    projectId: 'netravest-326c7',
    authDomain: 'netravest-326c7.firebaseapp.com',
    storageBucket: 'netravest-326c7.firebasestorage.app',
    measurementId: 'G-XRV1DEB0N1',
  );
}
